In [3]:
from sdv.datasets.demo import get_available_demos
from sdv.datasets.demo import download_demo
get_available_demos(modality='single_table')

              dataset_name  size_MB  num_tables
0                   KRK_v1     0.07           1
1                    adult     3.91           1
2                    alarm     4.52           1
3                     asia     1.28           1
4                   census    98.17           1
5          census_extended     4.95           1
6                    child     3.20           1
7                  covtype   255.65           1
8                   credit    68.35           1
9       expedia_hotel_logs     0.20           1
10          fake_companies     0.00           1
11       fake_hotel_guests     0.03           1
12                    grid     0.32           1
13                   gridr     0.32           1
14               insurance     3.34           1
15               intrusion   162.04           1
16                 mnist12    81.20           1
17                 mnist28   439.60           1
18                    news    18.71           1
19                    ring     0.32           1
20      student_placements     0.03           1
21  student_placements_pii     0.03           1

In [4]:
data, metadata = download_demo(
    modality='single_table',
    dataset_name='student_placements'
)

In [5]:
from sdv.single_table import CTGANSynthesizer

synthesizer = CTGANSynthesizer(metadata)
synthesizer.fit(data)

synthetic_data = synthesizer.sample(num_rows=10)

In [6]:
from sdv.single_table import CTGANSynthesizer

synthesizer = CTGANSynthesizer(
    metadata, # required
    enforce_rounding=False,
    epochs=500,
    verbose=True
)

In [7]:
synthesizer.get_parameters()

{'enforce_min_max_values': True,
 'enforce_rounding': False,
 'locales': None,
 'embedding_dim': 128,
 'generator_dim': (256, 256),
 'discriminator_dim': (256, 256),
 'generator_lr': 0.0002,
 'generator_decay': 1e-06,
 'discriminator_lr': 0.0002,
 'discriminator_decay': 1e-06,
 'batch_size': 500,
 'discriminator_steps': 1,
 'log_frequency': True,
 'verbose': True,
 'epochs': 500,
 'pac': 10,
 'cuda': True}

In [8]:
metadata = synthesizer.get_metadata()

In [9]:
synthesizer.fit(data)

Gen. (-0.44) | Discrim. (-0.25): 100%|██████████| 500/500 [00:39<00:00, 12.50it/s]

In [10]:
synthesizer.get_loss_values()

     Epoch   Generator Loss Discriminator Loss
0        0   tensor(1.0042)     tensor(0.0073)
1        1   tensor(0.9450)     tensor(0.0032)
2        2   tensor(0.9347)    tensor(-0.0272)
3        3   tensor(0.9715)    tensor(-0.0215)
4        4   tensor(0.9458)    tensor(-0.0395)
..     ...              ...                ...
495    495  tensor(-0.4956)    tensor(-0.2110)
496    496  tensor(-0.5357)    tensor(-0.3564)
497    497  tensor(-0.5005)    tensor(-0.1888)
498    498  tensor(-0.3842)    tensor(-0.5068)
499    499  tensor(-0.4373)    tensor(-0.2544)

[500 rows x 3 columns]

In [11]:
synthesizer.save(
    filepath='my_synthesizer.pkl'
)

In [14]:
from sdv.evaluation.single_table import run_diagnostic, evaluate_quality
from sdv.evaluation.single_table import get_column_plot

# 1. perform basic validity checks
diagnostic = run_diagnostic(data, synthetic_data, metadata)

# 2. measure the statistical similarity
quality_report = evaluate_quality(data, synthetic_data, metadata)

Generating report ...
(1/2) Evaluating Data Validity: : 100%|██████████| 17/17 [00:00<00:00, 4905.28it/s]
(2/2) Evaluating Data Structure: : 100%|██████████| 1/1 [00:00<00:00, 499.32it/s]

Overall Score: 100.0%

Properties:
- Data Validity: 100.0%
- Data Structure: 100.0%
Generating report ...
(1/2) Evaluating Column Shapes: : 100%|██████████| 17/17 [00:00<00:00, 1631.65it/s]
(2/2) Evaluating Column Pair Trends: : 100%|██████████| 136/136 [00:00<00:00, 166.77it/s]

Overall Score: 68.4%

Properties:
- Column Shapes: 76.91%
- Column Pair Trends: 59.89%